### ISSUE TITLE
Fix BookmarkTableViewCell ContentView BackgroundColor and Etc..

### ISSUE THREAD

**Issue by ApplePod** [sangyong-99/Team-ARTX-PoliceScience#117]
## 📌  Description
ContentView BackgroundColor 수정

## 📝  To-do

- [ ] ContentView BackgroundColor 수정
- [ ] QuizModalViewController Text Color 수정
- [ ] QuestionModel 레퍼런스 참조 삭제
