### ISSUE TITLE
Add SettingView

### ISSUE THREAD

**Issue by sangyong-99** [sangyong-99/Team-ARTX-PoliceScience#5]
## 📌  Description
SettingView의 초기 화면

## 📝  To-do

- [x] navigation 연결
- [x] navigation bar 디자인 변경
- [x] TableView
- [x] TableViewCell
- [x] 인증코드 등록 alert
- [x] 인증코드 firestore연동
- [x] 인증코드 완료 실패 alert
- [x] 인증코드 등록 미등록 label
- [x] 기기변경 alert
- [x] 기기변경 firestore
- [x] 학습기록 초기화 alert
