### ISSUE TITLE
QuizView: Fix UI detail

### ISSUE THREAD

**Issue by Medi0202** [sangyong-99/Team-ARTX-PoliceScience#97]
## 📝  To-do

- [x] 전체 문제 개수 불러오기 (예: 0/30)
- [x] Chapter 라벨 : "CHAPTER 01"
- [x] 프로그레스 바 두께
- [x] 프로그레스 바 계산식
- [x] 하트 아이콘 -> .iconCompletion-true
- [x] 라벨 : Quiz... 이라고 잘리는 부분
- [x] O, X 버튼 쉐도우
- [x] 퀴즈뷰 들어왔을 때 프로그레스바 업데이트
