### ISSUE TITLE
HomeView: Fix UI Detail

### ISSUE THREAD

**Issue by Medi0202** [sangyong-99/Team-ARTX-PoliceScience#98]
## 📝  To-do

- [ ] 챕터 문제 숫자 : 라벨 대신 자물쇠
- [ ] 조현 경찰학 타이틀 글씨체 변경 Gmarket Sans
- [ ] 프로그레스 바 아이콘 : 변경되는 애니메이션
